# Generated by Django 5.2 on 2025-04-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='pairs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
